### ISSUE TITLE
gcc6 build show incorrect dynamic libs

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew-versions#1116]
_From @gaming-hacker on January 14, 2016 18:54_

yoiu need to fix your install ENV as current install is to
**${HOMEBREW_PREFIX}/Cellar/gcc6/6-20160110_1/lib/gcc/6**

your libs report the following

**libgomp.1.dylib:
	 ${HOMEBREW_PREFIX}/opt/gcc6/lib/gcc/6/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	 ${HOMEBREW_PREFIX}/lib/gcc/6/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)**

_Copied from original issue: Homebrew/homebrew#48080_

**Comment by mistydemeo** [comment]
The `Cellar` location you're mentioning gets symlinked to `HOMEBREW_PREFIX/lib`. We intentionally make the install_names point to `HOMEBREW_PREFIX/lib` in order to make sure that `install_name`s for things which link to `libgcc_s` are okay - see the discussion starting here. https://github.com/Homebrew/homebrew/pull/34303#issuecomment-63732606

**Comment by mikemcquaid** [comment]
> The Cellar location you're mentioning gets symlinked to HOMEBREW_PREFIX/lib. We intentionally make the install_names point to HOMEBREW_PREFIX/lib in order to make sure that install_names for things which link to libgcc_s are okay - see the discussion starting here. Homebrew/homebrew#34303 (comment)

Sounds like this isn't a bug.
