### ISSUE TITLE
MySQL 5.6.29 update

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/homebrew-versions#1153]
Is there any reason why the mysql56 version hasn't been updated from 5.6.27 to 5.6.29?

https://github.com/Homebrew/homebrew-versions/blob/master/mysql56.rb

Can that be updated?

**Comment by DomT4** [comment]
> Is there any reason why the mysql56 version hasn't been updated from 5.6.27 to 5.6.29?

Because people dump formulae in Versions and then never come back to update them essentially, and the maintainers are kept busy enough in the core to need community help with Versions :smile:.

We'd absolutely love a PR to handle the update if you'd like to file one? There's some documentation [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) which applies to the core but easily applied to Versions as well.

**Comment by rgoldberg** [comment]
I might be able to help out in the future, but am too busy right now.

Thanks for the info.
