### ISSUE TITLE
gcc --version = gcc (Homebrew gcc6 6-20160320) 6.0.0 20160320 (experimental)

### ISSUE THREAD

**Issue by gilgameshskytrooper** [Homebrew/homebrew-versions#1272]
So installing this version of gcc, when i do a gcc --version command, it shows up as gcc 6.0.0

According to the documentation, shouldn't it be gcc 6.1?

Thanks

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by gilgameshskytrooper** [comment]
This is not an actual issue, and more of a request for clarification.

I installed gcc6 via homebrew using the appropriate commands, and added a symbolic link for gcc6

When I run the following command in terminal

`gcc --version`

I get the following result

`gcc (Homebrew gcc6 6-20160320) 6.0.0 20160320 (experimental)`
`Copyright (C) 2016 Free Software Foundation, Inc.`
`This is free software; see the source for copying conditions.  There is NO`
`warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

But according to the documentation on Github, it should be gcc 6.1.0 right?

Just wondering why it is showing up as "experimental." Also, when will a stable version of gcc 6 come to homebrew?

**Comment by UniqMartin** [comment]
I suspect you have installed the `gcc6` formula when it was still in development and before 6.1.0 was released? Unfortunately, because we picked `6-<date>` as the version number back then, Homebrew won't automatically detect that it needs to upgrade the formula now, because 6.1.0 compares less than 6-20160320. (It's comparing the second version component and 1 is less than 20160320.)

If you check with `brew info gcc6` then it should show that you have indeed version `6-20160320` installed as `gcc --version` is reporting. The workaround is to `brew uninstall gcc6` followed by `brew install gcc6`. This should lead to an installation of version 6.1.0.

**Comment by UniqMartin** [comment]
> Also, when will a stable version of gcc 6 come to homebrew?

An update of the `gcc` formula in Homebrew's main formula repository (`homebrew/core`) is in progress as Homebrew/homebrew-core#676 but is currently blocked by other changes that need to happen first. (You can check out the last few comments in the linked PR to learn more.)

**Comment by DomT4** [comment]
> Unfortunately, because we picked 6-<date> as the version number back then, Homebrew won't automatically detect that it needs to upgrade the formula now, because 6.1.0 compares less than 6-20160320.

This was discussed in https://github.com/Homebrew/homebrew-versions/pull/1256 for the sake of historical clarity.
