### ISSUE TITLE
Install subversion17 fails on El Capitan

### ISSUE THREAD

**Issue by davidbecher** [Homebrew/homebrew-versions#1397]
Hey there!

I realized that currently it is not possible to install subversion17 with El Capitan.

Right here https://github.com/Homebrew/legacy-homebrew/issues/49263 it was already discussed, but it seems not to give any indication on how to actually solve the problem.

I am working on a subversion respository which is rooted in svn 1.7. and it is currently also now an option to just update the repository to the newer version, because then all my other fellow team members would have to upgrade their svn version.

Is there currently a way to install subversion17 on my Mac with brew or any other tools?

All the best,
David

**Comment by MikeMcQuaid** [comment]
> Is there currently a way to install subversion17 on my Mac with brew or any other tools?

It seems not currently. We'll accept a pull-request to fix it but we don't actively work on fixing old versions on newer macOS versions ourselves, sorry!

**Comment by DomT4** [comment]
Basically:

* Remove SSL support. We tried this in the past and people held a small riot, so we put it back.
* Vendor in OpenSSL 0.9.8, which is completely unsupported upstream and hasn't been receiving security fixes or even security analysis since the end of last year.

No other combination seems to work. Really I'd go so far as to say we're already letting users use insecure software with `subversion17` that links to the outdated OpenSSL on Yosemite and below, but there we go.
