### ISSUE TITLE
Mono3 

### ISSUE THREAD

**Issue by ckchow** [Homebrew/homebrew-versions#1401]
When I try to install mono3, I get the following error:

```
curl: (7) Failed to connect to storage.bos.xamarin.com port 80: Connection refused
Error: Failed to download resource "mono3--monolite"
Download failed: http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz
```

I have looked around online and I'm not sure where you can download monolite anymore. Maybe from the mono project's Jenkins?

**Comment by MikeMcQuaid** [comment]
Maybe this old version just needs removed. Otherwise, could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by MikeMcQuaid** [comment]
When I migrate this formula to Homebrew/core I will either fix it or delete it. If you use it I recommend trying to submit a pull-request here to fix it before I remove it. Thanks!

**Comment by patspam** [comment]
This still appears to be an issue:

```
curl: (7) Failed to connect to storage.bos.xamarin.com port 80: Operation timed out
Error: Failed to download resource "mono3--monolite"
Download failed: http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz
```

**Comment by MikeMcQuaid** [comment]
> If you use it I recommend trying to submit a pull-request here to fix it before I remove it.

@patspam ☝️
