### ISSUE TITLE
Can't install v8-315 on OSX Sierra

### ISSUE THREAD

**Issue by GarPit** [Homebrew/homebrew-versions#1519]
Can't install v8-315 on OSX 10.12:

https://gist.github.com/anonymous/55bfb48d002d78f62a8e024a2911c337

**Comment by academikuser** [comment]
so, what is the exact work around?
trying to 

    R
    >
    install.packages("tmap")


* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=-I/usr/local/opt/v8-315/include
Using PKG_LIBS=-L/usr/local/opt/v8-315/lib -lv8
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because  was not found. Try installing:
 * deb: libv8-3.14-dev (formerly: libv8-dev) (Debian, Ubuntu)
 * rpm: v8-314-devel (formerly: v8-devel) (Fedora, EPEL)
 * brew: v8-315 (OSX) -- NOT regular v8! Tap from homebrew/versions
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'

**Comment by academikuser** [comment]
try this 

    brew tap homebrew/versions
    brew install v8-315
