### ISSUE TITLE
install hdf4 --enable-fortran doesn't seem to enable fortran

### ISSUE THREAD

**Issue by mjtamlyn** [Homebrew/homebrew-versions#683]
Firstly a minor complaint - the `hdf5` package from homebrew-science takes `--with-fortran` and the `hdf4` package takes `--enable-fortran`, which is kinda confusing.

The more serious complaint is that `--enable-fortran` doesn't seem to work.

On my system (Yosemite, netcdf installed but unlinked), I get the following output from `brew install hdf4 --debug --verbose --enable-fortran`: https://gist.github.com/mjtamlyn/5a3ae33cdd004e85d3c5

After than my cellar looks like: https://gist.github.com/mjtamlyn/aa80effbcf33f3b5065a Note the lack of any `.mod` or `.f90` files.

**Comment by DomT4** [comment]
>  which is kinda confusing.

Homebrew-science modernised the formula to match Homebrew/Homebrew's new preferred stylistic changes in regards to option naming. A lot of that hasn't filtered through to versions yet because the versions stuff tends to be by its nature rather old and less frequently updated. I've penned #685 to fix that issue at least.

> Note the lack of any .mod or .f90 files.

This is odd for Fortran stuff, but I confess I avoid trying to understand Fortran's particularities to save my own sanity as much as possible. Going to ping @iml and @mistydemeo for any thoughts on that :heart:.

**Comment by DomT4** [comment]
I've tried various tweaks to the build process and haven't found any difference in outcomes. Agree there are differences in the end-product between ` hdf4 ` and ` hdf5 ` around Fortran ` .mod ` files, but there's nothing in the documentation of ` hdf4 ` to suggest why that would happen - I'm left wondering if the difference is intended by upstream, although I've not yet found an answer to that.

Does the error reproduce if you build ` hdf4 ` outside of Homebrew with the same options?

I was hoping by now Homebrew/Science would have had the chance to look this over, given this is essentially a version of their formula, but evidently no dice on that. Welcome contribution from @Homebrew/owners on why the difference could have occurred here.
