### ISSUE TITLE
boot2docker13 ?

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-versions#731]
Could someone add boot2docker 1.3 to homebrew-versions, for working with Google Cloud? This old formula is:

https://github.com/Homebrew/homebrew/blob/5581b1604842b27fc351ae4c0838f9c5124729c2/Library/Formula/boot2docker.rb

**Comment by DomT4** [comment]
We don't really do requests as such, otherwise we'd drown in them :smile_cat:. It's an easy enough thing to do though if you want to try and submit a PR. Just essentially import that formula, add a ` revision ` tag to the ` url ` pointing to the relevant upstream commit the tag was based on, rename it ` boot2docker13 `, remove the bottle block and you're done.
