### ISSUE TITLE
Povray can't be installed

### ISSUE THREAD

**Issue by adius** [Homebrew/homebrew-versions#754]
```
$ brew install homebrew/versions/povray36
==> Installing povray36 from homebrew/homebrew-versions
==> Downloading http://www.povray.org/ftp/pub/povray/Official/Unix/povray-3.6.1.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "povray36"
Download failed: http://www.povray.org/ftp/pub/povray/Official/Unix/povray-3.6.1.tar.bz2
```

**Comment by DomT4** [comment]
Upstream URL has moved. They've shifted the source packages to Github and moved the old archived source packages to http://www.povray.org/ftp/pub/povray/Old-Versions/. Feel free to submit a PR with the fix if you like, otherwise I'll do so later this evening. If you submit a PR, if you could also fix any issues highlighted by ` brew audit --strict ` on that formula I'd be grateful.
