### ISSUE TITLE
versions/lua53 install header files to wrong path

### ISSUE THREAD

**Issue by tangyi** [Homebrew/homebrew-versions#972]
While lua52 installs header files to `/usr/local/include/` , versions/lua53 installs them to `/usr/local/include/lua5.3`.

When I build HAProxy-1.6, it can not find lua  which I installed with homebrew.

**Comment by DomT4** [comment]
This is intentional, and the same behaviour that applies to `lua51`, otherwise all the header files would ram into each other and cause conflict.

The `pkg-config` file points at the right directory, so anything that can use pkg-config should be fine. Otherwise you can pass the install stage an extra `CFLAGS` pointer to the path.
